### ISSUE TITLE
%%writefile causes error

### ISSUE THREAD

**Issue by cliveseldon** [kubeflow-kale/kale#164]
if you have a pipeline cell

```
%%writefile sa.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-sa
secrets:
  - name: container-secret
```

Compile this with current master you will get an error.

```
Message: Flakes reported the following error:
	kale:6:10: invalid syntax
	metadata:	
	         ^
```
