### ISSUE TITLE
Make autogen Katib Trial/Job template configurable

### ISSUE THREAD

**Issue by prashanthb-ai** [kubeflow-kale/kale#320]
This is basically a x-post of a Katib issue I created: https://github.com/kubeflow/katib/issues/1454#issuecomment-791474023. I would like to remove some key annotations from a Katib Experiment Job template, without having to modify and kubectl create the yaml myself (..which I actually can't do as there is no "Compile and Save Katib Job" option; so I have to change the name and delete the first run myself). 

Eg, I see this in the autogen experiment yaml: 
```yaml
kind: Job
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
        labels:
          access-ml-pipeline: 'true'
```
I'd like to remove `sidecar.istio.io/inject`, and possibly modify `access-ml-pipeline` (my poddefaults are different). 

The core issue, as descriibed in the Katib bug, is that I need istio to inject the `kubeflow-userid` header. Is there a more elegant workaround I'm missing?
